Fix block limit upgrade
Iridium-Development/IridiumSkyblock pull request #300
Opened 2021-07-21 08:56 UTC by xReveres

Fixes enabling/disabling block limit upgrade

2021-07-21 09:05 UTC, PeachesMLG commented
Not sure I like this, mabey they dont want a block limit upgrade but still want block limits? in which case they can change the limits for the level 1 upgrade, if they dont want limits or an upgrade then they just need to remove all the limits from level 1?

2021-07-21 10:03 UTC, xReveres commented
I thought property "enabled" is for whole upgrade not for only display icon in upgrade GUI, but also you have right, so maybe we can add new property "displayInGUI: true/false" or add support for "slot: -1" if they dont want display it, but want limit/block something?

2021-07-21 18:22 UTC, dlsf requested changes
Very important

2021-07-21 18:22 UTC, dlsf commented on src/main/java/com/iridium/iridiumskyblock/listeners/BlockPlaceListener.java
> +        if(IridiumSkyblock.getInstance().getUpgrades().blockLimitUpgrade.enabled) {
```suggestion
        if (IridiumSkyblock.getInstance().getUpgrades().blockLimitUpgrade.enabled) {
```

2021-07-22 09:44 UTC, dlsf approved these changes

2021-07-22 11:42 UTC, PeachesMLG commented
> I thought property "enabled" is for whole upgrade not for only display icon in upgrade GUI, but also you have right, so maybe we can add new property "displayInGUI: true/false" or add support for "slot: -1" if they dont want display it, but want limit/block something?

I dont see the issue with the system we have no, its the same for every upgrade. For example the size upgrade, if enabled is true its saying we can upgrade it, if its false we cant upgrade it, but we will still have a size, its just you cant upgrade the size so it uses level 1 as a default, same with every other upgrade?

2021-07-22 11:46 UTC, xReveres commented
Yes you have right, my mistake.
My idea was to make a little "performance" to omit few lines of code and checks.

2021-07-22 11:46 UTC, closed without merging