Per-Placeholder Default Values
Iridium-Development/IridiumSkyblock pull request #327
Opened 2021-07-29 16:55 UTC by Oribuin

This adds the ability for people to customize the default values for each individual placeholders instead of a global one.

This will use placeholders.yml

2021-07-29 17:03 UTC, PeachesMLG approved these changes
Looks good to me, but im dum so @dlsf ?

2021-07-29 17:23 UTC, dlsf requested changes

2021-07-29 17:23 UTC, dlsf commented on src/main/java/com/iridium/iridiumskyblock/configs/Placeholders.java
> +    public String island_name = "N/A";
I'm afraid this isn't python, please use lowerCamelCase 👀

2021-07-29 17:38 UTC, MertUnverdi approved these changes
we don't need new config files but peaches is dum

2021-07-29 17:41 UTC, dlsf approved these changes
No, Ry is dum

2021-07-30 08:47 UTC, merged

2021-07-30 08:48 UTC, PeachesMLG commented
Ry very dum