add option to disable patreon message
Iridium-Development/IridiumSkyblock pull request #330
Opened 2021-07-30 18:01 UTC by Oribuin

please add this, it took me a whole 30 seconds to create this feature and id really appreciate it if you didnt make me waste a whole 30s on making this change

also it can be kinda annoying so to save the whining from people in #support, just merge it, we'd all be better off

2021-07-30 18:03 UTC, MertUnverdi commented
close it dum, we won't remove that message (for some users should stay there)👍🏻

2021-07-30 18:04 UTC, Oribuin commented
> close it dum, we won't remove that message (for some users should stay there)👍🏻

i will find your family and bonk you upside the noggin bruv

2021-07-30 18:04 UTC, Oribuin commented
the build failed because Esophose is moving the rosewood repo, I'm not a bad developer I promise

2021-07-30 18:04 UTC, dlsf requested changes

2021-07-30 18:04 UTC, dlsf commented on src/main/java/com/iridium/iridiumskyblock/listeners/PlayerJoinQuitListener.java
> +        if (player.isOp() && IridiumSkyblock.getInstance().getConfiguration().patreonMessage) {
This code can be simplified
```suggestion
        if (player.isOp() && true) {
```

2021-07-30 18:05 UTC, MertUnverdi commented on src/main/java/com/iridium/iridiumskyblock/listeners/PlayerJoinQuitListener.java
> +        if (player.isOp() && IridiumSkyblock.getInstance().getConfiguration().patreonMessage) {
LOOOL

2021-07-31 20:59 UTC, PeachesMLG commented
You know I really liked having this because it would annoy everyone, but fine >:C

2021-07-31 20:59 UTC, merged