Made Bank Items' names in messages configurable and added message for crystal deposit
Iridium-Development/IridiumSkyblock pull request #392
Opened 2021-09-07 10:40 UTC by Faun471

I think peaches has a reason why the bank item names in messages aren't changeable, so I can remove it if needed

2021-09-13 18:24 UTC, MertUnverdi requested changes

2021-09-13 18:24 UTC, MertUnverdi commented on src/main/java/com/iridium/iridiumskyblock/bank/ExperienceBankItem.java
> +                        .replace("%type%", getName())
make these capitalized, it will return `experience`

2021-09-13 18:24 UTC, MertUnverdi commented on src/main/java/com/iridium/iridiumskyblock/bank/ExperienceBankItem.java
> +                        .replace("%type%", getName())
or just add another getter in BankItems :panda:

2021-09-16 04:11 UTC, MertUnverdi requested changes
Also displayName will be null on exiting configs use an hardcode for setting defaults (i prefer Reflection#getCaller)

2021-09-16 04:11 UTC, MertUnverdi commented on src/main/java/com/iridium/iridiumskyblock/bank/MoneyBankItem.java
> +        super("money", "money", defaultAmount, true, item);
```suggestion
        super("money", "Money", defaultAmount, true, item);
```

2021-09-16 04:11 UTC, MertUnverdi commented on src/main/java/com/iridium/iridiumskyblock/bank/ExperienceBankItem.java
> +                        .replace("%type%", getName())
```suggestion
                        .replace("%type%", getDisplayName())
```

2021-09-16 04:11 UTC, MertUnverdi commented on src/main/java/com/iridium/iridiumskyblock/bank/ExperienceBankItem.java
> +                        .replace("%type%", getName())
```suggestion
                        .replace("%type%", getDisplayName())
```

2021-09-16 04:11 UTC, MertUnverdi commented on src/main/java/com/iridium/iridiumskyblock/bank/ExperienceBankItem.java
> +                        .replace("%type%", getName())
```suggestion
                        .replace("%type%", getDisplayName())
```

2021-09-16 04:11 UTC, MertUnverdi commented on src/main/java/com/iridium/iridiumskyblock/bank/ExperienceBankItem.java
> +                        .replace("%type%", getName())
```suggestion
                        .replace("%type%", getDisplayName())
```

2021-09-16 04:11 UTC, MertUnverdi commented on src/main/java/com/iridium/iridiumskyblock/bank/ExperienceBankItem.java
> +        super("experience", "experience", defaultAmount, true, item);
```suggestion
        super("experience", "Experience", defaultAmount, true, item);
```

2021-09-16 04:11 UTC, MertUnverdi commented on src/main/java/com/iridium/iridiumskyblock/bank/CrystalsBankItem.java
> +                        .replace("%type%", getName())
```suggestion
                        .replace("%type%", getDisplayName())
```

2021-09-16 04:11 UTC, MertUnverdi commented on src/main/java/com/iridium/iridiumskyblock/bank/CrystalsBankItem.java
> +                        .replace("%type%", getName())
```suggestion
                        .replace("%type%", getDisplayName())
```

2021-09-16 04:11 UTC, MertUnverdi commented on src/main/java/com/iridium/iridiumskyblock/bank/CrystalsBankItem.java
> +        super("crystals", "crystals", defaultAmount, true, item);
```suggestion
        super("crystals", "Crystals", defaultAmount, true, item);
```

2021-09-17 08:11 UTC, dlsf approved these changes

2021-09-19 06:38 UTC, merged