Revert partiel Iridium-Development/IridiumSkyblock#384
Iridium-Development/IridiumSkyblock pull request #411
Opened 2021-09-28 23:46 UTC by DoctaEnkoda

2021-09-29 05:39 UTC, dlsf requested changes

2021-09-29 05:39 UTC, dlsf commented on src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/ForeignIslandTableManager.java
> +            if (island.equals(islandData.getIsland().orElse(null))) {
islandData can be null, the check for that should stay.

2021-09-29 08:31 UTC, PeachesMLG requested changes
Im kinda confused about what your trying to do here, this would break alot of changes and I dont see how it would fix missions

2021-09-29 08:31 UTC, PeachesMLG commented on src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/ForeignIslandTableManager.java
> +        int index = Collections.binarySearch(getEntries(), t, Comparator.comparing(t1 -> t1.getIsland().map(Island::getId).orElse(0)));
This shouldnt be needed, it should add it in its correctly sorted place if you look in TableManager and SortedList class

2021-09-29 08:31 UTC, PeachesMLG commented on src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/ForeignIslandTableManager.java
> +        getEntries().sort(Comparator.comparing(t1 -> t1.getIsland().map(Island::getId).orElse(0)));
This should be sorted using comparator? In Rewards case comparator is sorting by IslandID (which you can see in DatabaseManager)

2021-09-29 08:31 UTC, PeachesMLG commented on src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/IslandTableManager.java
> +        int index = Collections.binarySearch(getEntries(), island, Comparator.comparing(Island::getId));
Again this should be sorted using SortedList class

2021-09-29 08:31 UTC, PeachesMLG commented on src/main/java/com/iridium/iridiumskyblock/managers/tablemanagers/UserTableManager.java
> +        int index = Collections.binarySearch(getEntries(), user, Comparator.comparing(User::getUuid));
Again should be sorted using SortedList method

2021-10-01 16:59 UTC, PeachesMLG commented
Replaced by: https://github.com/Iridium-Development/IridiumSkyblock/pull/412

2021-10-01 16:59 UTC, closed without merging