Optimised Saving Data
Iridium-Development/IridiumSkyblock pull request #507
Opened 2021-11-17 11:52 UTC by PeachesMLG

2021-11-17 12:34 UTC, DoctaEnkoda commented
https://github.com/Iridium-Development/IridiumCore/pull/25

2021-11-20 16:52 UTC, DoctaEnkoda requested changes

2021-11-20 16:52 UTC, DoctaEnkoda commented on src/main/java/com/iridium/iridiumskyblock/database/Island.java
> +    }
SetSize dont work because he is not save in island database

2021-11-20 16:52 UTC, DoctaEnkoda commented on src/main/java/com/iridium/iridiumskyblock/database/User.java
> +    }
Bypass is not save in database

2021-11-20 16:52 UTC, DoctaEnkoda commented on src/main/java/com/iridium/iridiumskyblock/database/User.java
> +    }
Flying is not save in database

2021-11-20 16:52 UTC, DoctaEnkoda commented on src/main/java/com/iridium/iridiumskyblock/database/User.java
> +    }
Not save in database

2021-11-20 16:52 UTC, DoctaEnkoda commented on src/main/java/com/iridium/iridiumskyblock/database/User.java
> +    }
Not save in Database

2021-11-20 16:52 UTC, DoctaEnkoda commented on src/main/java/com/iridium/iridiumskyblock/database/User.java
> +    }
Not save in database

2021-11-20 16:52 UTC, DoctaEnkoda commented on src/main/java/com/iridium/iridiumskyblock/database/User.java
> +
Not save in database

2021-11-20 16:59 UTC, DoctaEnkoda commented
I think it's missing IslandBan

2021-11-20 22:26 UTC, PeachesMLG commented
> I think it's missing :
> 
>     * IslandsBans
> 
>     * IslandInvites
> 
>     * IslandLogs
> 
>     * IslandRewards
> 
>     * IslandTrusted

These are missing because these dont update, they just create/delete

Main thing I dont like about this pr is that if we forget to add setChanged, I was looking for a clever way to inject this into lombok or something somhow

2021-11-22 14:46 UTC, merged