Fix Fishing Missions
Iridium-Development/IridiumSkyblock pull request #526
Opened 2021-12-02 18:07 UTC by GavvyDizzle

The old code did not properly pass the material of the item that was caught.

2021-12-02 19:10 UTC, dlsf requested changes

2021-12-02 19:10 UTC, dlsf commented on src/main/java/com/iridium/iridiumskyblock/listeners/PlayerFishListener.java
> +        island.ifPresent(value -> IridiumSkyblock.getInstance().getMissionManager().handleMissionUpdates(value, "FISH", ((Item) caughtEntity).getItemStack().getType().toString(), 1));
Use Material#name(), it's just good practice 
```suggestion
        island.ifPresent(value -> IridiumSkyblock.getInstance().getMissionManager().handleMissionUpdates(value, "FISH", ((Item) caughtEntity).getItemStack().getType().name(), 1));
```

2021-12-02 19:25 UTC, PeachesMLG reviewed
Is Caught Entity always an item? I belive in some plugins they modify it so you can fish up tnt and stuff, should we add an instance check?

2021-12-02 19:51 UTC, GavvyDizzle commented
PlayerFishEvent.State.CAUGHT_FISH

When a player has successfully caught a fish and is reeling it in. In this instance, a "fish" is any item retrieved from water as a result of fishing, ie an item, but not necessarily a fish.

I think the check to make sure it is a CAUGHT_FISH guarentees that it is an item.

2021-12-12 16:22 UTC, dlsf commented
> Is Caught Entity always an item? I belive in some plugins they modify it so you can fish up tnt and stuff, should we add an instance check?

There is no way to alter the item that has been fished. I've written a fishing plugin myself, and I ended up having to re-code the entire Minecraft reel-in system just to change the item / entity that you fish. If I didn't overlook anything back then, the item will always be a fish, or else the event will have to be cancelled by the fishing plugin.

2021-12-12 16:22 UTC, dlsf approved these changes

2021-12-12 16:36 UTC, merged