Fix issue with +54 rewards
Iridium-Development/IridiumSkyblock pull request #568
Opened 2022-01-16 17:24 UTC by DoctaEnkoda

2022-01-16 18:05 UTC, dlsf commented on src/main/java/com/iridium/iridiumskyblock/gui/IslandRewardsGUI.java
> +            if (atomicInteger.get() > maxSize) continue;
You can just break, can't you?

2022-01-16 18:15 UTC, DoctaEnkoda commented on src/main/java/com/iridium/iridiumskyblock/gui/IslandRewardsGUI.java
> +            if (atomicInteger.get() > maxSize) continue;
yes mb

2022-01-16 18:26 UTC, dlsf approved these changes

2022-01-17 18:00 UTC, PeachesMLG commented
Good spot, if we are adding this, I think we should add next page / previous page buttons aswell

2022-01-17 18:00 UTC, PeachesMLG requested changes
Good spot, if we are adding this, I think we should add next page / previous page buttons aswell

2022-01-17 18:04 UTC, dlsf commented
I don't really feel like that's needed, rewards just appear after you claim them. Why would you want to claim a specific reward?

2022-01-17 18:18 UTC, PeachesMLG commented
idk, people are weird

2022-02-04 22:13 UTC, dlsf commented
@DoctaEnkoda are you planning on adding pagination support or should someone else do it?

2022-02-05 06:18 UTC, DoctaEnkoda commented
Frankly, the pagination is useless because we only recover. Why weigh down something that doesn't need it.

2022-02-06 12:37 UTC, merged