Increase default money withdrawal amount
Iridium-Development/IridiumSkyblock pull request #599
Opened 2022-02-05 14:05 UTC by dlsf

10 is **very** little money

2022-02-05 14:35 UTC, PeachesMLG commented
I think this should be 1k

2022-02-05 18:29 UTC, PeachesMLG approved these changes
changed to 1k

2022-02-05 18:29 UTC, PeachesMLG requested changes
changed to 1k

2022-02-05 18:30 UTC, PeachesMLG commented
Well, I tried editing this myself, but it wouldnt let me commit :cry:

2022-02-05 22:12 UTC, dlsf commented on src/main/java/com/iridium/iridiumskyblock/configs/BankItems.java
> +    public MoneyBankItem moneyBankItem = new MoneyBankItem(100, new Item(XMaterial.PAPER, 11, 1, "&b&lIsland Money", Arrays.asList("&7$%amount%", "&b&l[!] &bLeft click to withdraw", "&b&l[!] &bRight
```suggestion
    public MoneyBankItem moneyBankItem = new MoneyBankItem(1000, new Item(XMaterial.PAPER, 11, 1, "&b&lIsland Money", Arrays.asList("&7$%amount%", "&b&l[!] &bLeft click to withdraw", "&b&l[!] &bRight click to deposit")));
```

2022-02-05 22:12 UTC, dlsf commented
If nothing works, just suggest the change and commit it yourself

2022-02-06 12:32 UTC, PeachesMLG commented
> If nothing works, just suggest the change and commit it yourself

I tried lol, too dum ig

2022-02-06 12:32 UTC, merged