Optimization Position Verification.
Iridium-Development/IridiumSkyblock pull request #614
Opened 2022-02-14 08:11 UTC by DoctaEnkoda

2022-02-14 15:26 UTC, dlsf commented
When exactly is the world null? What does this improve?

2022-02-15 05:08 UTC, DoctaEnkoda commented
He is null when check : Island#isInIsland()
And call when : 
- Island#isInIsland() + screen
- IslandManager#recalculateIsland()

With 100 players on my server, we lost 8% tick with calcul function and it always call without player too.
![image](https://user-images.githubusercontent.com/26461373/153996356-c8932c9b-7342-47e0-a1ab-ec5ee780dc0c.png)

2022-02-15 21:01 UTC, dlsf commented
Did you test the performance impact of your change, by any chance?

2022-02-16 05:54 UTC, DoctaEnkoda commented
Like I said, I was practically at 8% tick minimum on 100 players, especially on entity damage which was infamous on the mspt.

I can't redo spark because I'm using this modified version but yeah, went from 8% to 0.7% tick, that's pretty huge

2022-02-16 12:07 UTC, dlsf requested changes
The rest looks fine

2022-02-16 12:07 UTC, dlsf commented on src/main/java/com/iridium/iridiumskyblock/database/Island.java
> +        }
```suggestion
        }
        
```

2022-02-16 12:07 UTC, dlsf commented on src/main/java/com/iridium/iridiumskyblock/database/Island.java
> +        }
```suggestion
        }
        
```

2022-02-16 12:07 UTC, dlsf commented on src/main/java/com/iridium/iridiumskyblock/database/Island.java
> +    private final Cache<Location> locationCachePos1 = new Cache<>(5000);
I don't know if `pos1Cache` or `pos1LocationCache` would be better, this sounds a bit weird, but you don't have to change it if you don't want to

2022-02-20 11:40 UTC, merged