Fix Big LAG when spam next page visit gui !
Iridium-Development/IridiumSkyblock pull request #619
Opened 2022-02-17 13:40 UTC by DoctaEnkoda

Occurs when retrieving the UUID from the Mojang API.
Too many requests can crash the server!
Even the Bukkit.getOfflinePlayer is not enough because it is very slow!

Need : 
- https://github.com/Iridium-Development/IridiumCore/pull/31 (Support UUID Item)
- https://github.com/Iridium-Development/IridiumCore/pull/32 (Check UUID Exist in Item)

2022-02-17 14:49 UTC, dlsf requested changes
Rest looks good

2022-03-08 17:02 UTC, dlsf approved these changes

2022-03-20 14:17 UTC, PeachesMLG commented
Gonna be honest, I dont really like this, but only because it removes a bit of configurability.

What if somone doesnt want to have a player head in the /is members GUI?

Or is this chance so low that das will tell me to shut up and merge it? :thinking:

2022-07-02 09:33 UTC, DoctaEnkoda commented
Close because conflict

2022-07-02 09:33 UTC, closed without merging